"""Дополнительные оптимизации (подключаются в tweaks.TWEAKS)."""
P = r"HKLM\SOFTWARE\Policies\Microsoft"
CDM = r"HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"
ADV = r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
MM = r"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile"


def add(key, name, t, data):
    return f'reg add "{key}" /v "{name}" /t {t} /d {data} /f'


def dele(key, name):
    return f'reg delete "{key}" /v "{name}" /f'


def task(path, on):
    return f'schtasks /Change /TN "{path}" /{"ENABLE" if on else "DISABLE"}'


_TELE_TASKS = [
    r"\Microsoft\Windows\Customer Experience Improvement Program\Consolidator",
    r"\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip",
    r"\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser",
    r"\Microsoft\Windows\Application Experience\ProgramDataUpdater",
    r"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector",
    r"\Microsoft\Windows\Feedback\Siuf\DmClient",
]

EXTRA = [
    ("widgets", "Виджеты и «Новости и интересы»",
     "Отключает панель виджетов на панели задач",
     [add(P + r"\Dsh", "AllowNewsAndInterests", "REG_DWORD", 0)],
     [dele(P + r"\Dsh", "AllowNewsAndInterests")]),
    ("cortana", "Cortana", "Отключает голосового помощника",
     [add(P + r"\Windows\Windows Search", "AllowCortana", "REG_DWORD", 0)],
     [dele(P + r"\Windows\Windows Search", "AllowCortana")]),
    ("websearch", "Bing в поиске меню Пуск", "Поиск Windows ищет только на компьютере",
     [add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\Search", "BingSearchEnabled", "REG_DWORD", 0),
      add(r"HKCU\Software\Policies\Microsoft\Windows\Explorer", "DisableSearchBoxSuggestions", "REG_DWORD", 1)],
     [add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\Search", "BingSearchEnabled", "REG_DWORD", 1),
      dele(r"HKCU\Software\Policies\Microsoft\Windows\Explorer", "DisableSearchBoxSuggestions")]),
    ("tele_tasks", "Задачи телеметрии в планировщике",
     "CEIP, Compatibility Appraiser, DiskDiagnostic, обратная связь",
     [task(t, False) for t in _TELE_TASKS], [task(t, True) for t in _TELE_TASKS]),
    ("advertising_id", "Рекламный идентификатор", "Приложения не получают рекламный ID",
     [add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo", "Enabled", "REG_DWORD", 0)],
     [add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo", "Enabled", "REG_DWORD", 1)]),
    ("lockscreen_ads", "Реклама на экране блокировки", "«Интересные факты» и советы Spotlight",
     [add(CDM, "RotatingLockScreenOverlayEnabled", "REG_DWORD", 0),
      add(CDM, "SubscribedContent-338387Enabled", "REG_DWORD", 0)],
     [add(CDM, "RotatingLockScreenOverlayEnabled", "REG_DWORD", 1),
      add(CDM, "SubscribedContent-338387Enabled", "REG_DWORD", 1)]),
    ("activity", "История действий (Timeline)", "Windows не собирает историю действий",
     [add(P + r"\Windows\System", "PublishUserActivities", "REG_DWORD", 0),
      add(P + r"\Windows\System", "UploadUserActivities", "REG_DWORD", 0)],
     [dele(P + r"\Windows\System", "PublishUserActivities"),
      dele(P + r"\Windows\System", "UploadUserActivities")]),
    ("recall", "Windows Recall / Copilot", "Отключает снимки экрана Recall и кнопку Copilot",
     [add(P + r"\Windows\WindowsAI", "DisableAIDataAnalysis", "REG_DWORD", 1),
      add(r"HKCU\Software\Policies\Microsoft\Windows\WindowsCopilot", "TurnOffWindowsCopilot", "REG_DWORD", 1)],
     [dele(P + r"\Windows\WindowsAI", "DisableAIDataAnalysis"),
      dele(r"HKCU\Software\Policies\Microsoft\Windows\WindowsCopilot", "TurnOffWindowsCopilot")]),
    ("menu_delay", "Мгновенные меню", "Убирает задержку всплывающих меню",
     [add(r"HKCU\Control Panel\Desktop", "MenuShowDelay", "REG_SZ", 0)],
     [add(r"HKCU\Control Panel\Desktop", "MenuShowDelay", "REG_SZ", 400)]),
    ("startup_delay", "Без паузы перед автозапуском",
     "Программы автозагрузки стартуют сразу, без искусственной задержки",
     [add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Serialize", "StartupDelayInMSec", "REG_DWORD", 0)],
     [dele(r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Serialize", "StartupDelayInMSec")]),
    ("fast_shutdown", "Быстрое завершение зависших программ",
     "Выключение ПК не ждёт подвисшие программы по 20 секунд",
     [add(r"HKCU\Control Panel\Desktop", "WaitToKillAppTimeout", "REG_SZ", 3000),
      add(r"HKCU\Control Panel\Desktop", "HungAppTimeout", "REG_SZ", 2000),
      add(r"HKCU\Control Panel\Desktop", "AutoEndTasks", "REG_SZ", 1)],
     [dele(r"HKCU\Control Panel\Desktop", "WaitToKillAppTimeout"),
      dele(r"HKCU\Control Panel\Desktop", "HungAppTimeout"),
      dele(r"HKCU\Control Panel\Desktop", "AutoEndTasks")]),
    ("power_throttling", "Отключить Power Throttling",
     "Windows перестаёт замедлять фоновые программы",
     [add(r"HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling", "PowerThrottlingOff", "REG_DWORD", 1)],
     [dele(r"HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling", "PowerThrottlingOff")]),
    ("gaming_mode", "Приоритет активному окну",
     "Планировщик отдаёт больше времени программе на переднем плане",
     [add(r"HKLM\SYSTEM\CurrentControlSet\Control\PriorityControl", "Win32PrioritySeparation", "REG_DWORD", 38)],
     [add(r"HKLM\SYSTEM\CurrentControlSet\Control\PriorityControl", "Win32PrioritySeparation", "REG_DWORD", 2)]),
    ("game_profile", "Мультимедиа-профиль для игр",
     "Повышенный приоритет GPU/CPU для игр, без резерва для фона",
     [add(MM, "SystemResponsiveness", "REG_DWORD", 10),
      add(MM + r"\Tasks\Games", "GPU Priority", "REG_DWORD", 8),
      add(MM + r"\Tasks\Games", "Priority", "REG_DWORD", 6),
      add(MM + r"\Tasks\Games", "Scheduling Category", "REG_SZ", "High")],
     [add(MM, "SystemResponsiveness", "REG_DWORD", 20),
      add(MM + r"\Tasks\Games", "GPU Priority", "REG_DWORD", 8),
      add(MM + r"\Tasks\Games", "Priority", "REG_DWORD", 2),
      add(MM + r"\Tasks\Games", "Scheduling Category", "REG_SZ", "Medium")]),
    ("net_throttle", "Без ограничения сети для мультимедиа",
     "Снимает NetworkThrottlingIndex (меньше задержки в играх и стримах)",
     [add(MM, "NetworkThrottlingIndex", "REG_DWORD", 4294967295)],
     [add(MM, "NetworkThrottlingIndex", "REG_DWORD", 10)]),
    ("hags", "Аппаратное планирование GPU (HAGS)",
     "Может поднять FPS и снизить задержку на современных видеокартах",
     [add(r"HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HwSchMode", "REG_DWORD", 2)],
     [add(r"HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HwSchMode", "REG_DWORD", 1)]),
    ("mouse_accel", "Без ускорения мыши", "«Повышенная точность указателя» выключена — для игр",
     [add(r"HKCU\Control Panel\Mouse", "MouseSpeed", "REG_SZ", 0),
      add(r"HKCU\Control Panel\Mouse", "MouseThreshold1", "REG_SZ", 0),
      add(r"HKCU\Control Panel\Mouse", "MouseThreshold2", "REG_SZ", 0)],
     [add(r"HKCU\Control Panel\Mouse", "MouseSpeed", "REG_SZ", 1),
      add(r"HKCU\Control Panel\Mouse", "MouseThreshold1", "REG_SZ", 6),
      add(r"HKCU\Control Panel\Mouse", "MouseThreshold2", "REG_SZ", 10)]),
    ("visual_perf", "Визуальные эффекты: быстродействие", "Без анимаций окон и прозрачности",
     [add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects", "VisualFXSetting", "REG_DWORD", 2),
      add(r"HKCU\Control Panel\Desktop\WindowMetrics", "MinAnimate", "REG_SZ", 0),
      add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "EnableTransparency", "REG_DWORD", 0),
      add(ADV, "TaskbarAnimations", "REG_DWORD", 0)],
     [add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects", "VisualFXSetting", "REG_DWORD", 0),
      add(r"HKCU\Control Panel\Desktop\WindowMetrics", "MinAnimate", "REG_SZ", 1),
      add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "EnableTransparency", "REG_DWORD", 1),
      add(ADV, "TaskbarAnimations", "REG_DWORD", 1)]),
    ("ntfs_lastaccess", "NTFS: не обновлять время доступа",
     "Меньше лишних записей на диск при каждом чтении файла",
     ["fsutil behavior set disablelastaccess 1"], ["fsutil behavior set disablelastaccess 2"]),
    ("edge_bg", "Edge: без фоновой работы", "Edge не висит в фоне и не стартует с Windows",
     [add(P + r"\Edge", "StartupBoostEnabled", "REG_DWORD", 0),
      add(P + r"\Edge", "BackgroundModeEnabled", "REG_DWORD", 0)],
     [dele(P + r"\Edge", "StartupBoostEnabled"), dele(P + r"\Edge", "BackgroundModeEnabled")]),
    ("bg_apps", "Фоновые приложения Store", "Запрещает UWP-приложениям работать в фоне",
     [add(P + r"\Windows\AppPrivacy", "LetAppsRunInBackground", "REG_DWORD", 2)],
     [dele(P + r"\Windows\AppPrivacy", "LetAppsRunInBackground")]),
    ("delivery_opt", "Оптимизация доставки (P2P обновлений)",
     "Windows не раздаёт обновления другим компьютерам через ваш интернет",
     [add(P + r"\Windows\DeliveryOptimization", "DODownloadMode", "REG_DWORD", 0)],
     [dele(P + r"\Windows\DeliveryOptimization", "DODownloadMode")]),
    ("show_ext", "Показывать расширения файлов", "Видно .exe/.txt — сложнее подсунуть вирус",
     [add(ADV, "HideFileExt", "REG_DWORD", 0)], [add(ADV, "HideFileExt", "REG_DWORD", 1)]),
    ("show_hidden", "Показывать скрытые файлы", "Проводник показывает скрытые файлы и папки",
     [add(ADV, "Hidden", "REG_DWORD", 1)], [add(ADV, "Hidden", "REG_DWORD", 2)]),
    ("classic_menu", "Классическое контекстное меню (Win 11)",
     "Полное меню правой кнопки без «Показать дополнительные параметры»",
     [r'reg add "HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /ve /f'],
     [r'reg delete "HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}" /f']),
    ("taskbar_left", "Панель задач слева (Win 11)", "Кнопки панели задач по левому краю",
     [add(ADV, "TaskbarAl", "REG_DWORD", 0)], [add(ADV, "TaskbarAl", "REG_DWORD", 1)]),
    ("this_pc", "Проводник открывает «Этот компьютер»", "Вместо «Главная»/«Быстрый доступ»",
     [add(ADV, "LaunchTo", "REG_DWORD", 1)], [add(ADV, "LaunchTo", "REG_DWORD", 2)]),
    ("clipboard_history", "История буфера обмена (Win+V)", "Хранит несколько скопированных фрагментов",
     [add(r"HKCU\Software\Microsoft\Clipboard", "EnableClipboardHistory", "REG_DWORD", 1)],
     [add(r"HKCU\Software\Microsoft\Clipboard", "EnableClipboardHistory", "REG_DWORD", 0)]),
    ("long_paths", "Длинные пути (> 260 символов)", "Снимает ограничение MAX_PATH",
     [add(r"HKLM\SYSTEM\CurrentControlSet\Control\FileSystem", "LongPathsEnabled", "REG_DWORD", 1)],
     [add(r"HKLM\SYSTEM\CurrentControlSet\Control\FileSystem", "LongPathsEnabled", "REG_DWORD", 0)]),
    ("verbose_boot", "Подробные сообщения при загрузке", "Видно, что Windows делает при старте/выключении",
     [add(r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "VerboseStatus", "REG_DWORD", 1)],
     [dele(r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "VerboseStatus")]),
    ("storage_sense", "Контроль памяти (автоочистка)", "Автоматически удаляет временные файлы",
     [add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy", "01", "REG_DWORD", 1)],
     [add(r"HKCU\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy", "01", "REG_DWORD", 0)]),
    ("sticky_keys", "Без окна «Залипание клавиш» (5× Shift)", "Не всплывает в играх",
     [add(r"HKCU\Control Panel\Accessibility\StickyKeys", "Flags", "REG_SZ", 506)],
     [add(r"HKCU\Control Panel\Accessibility\StickyKeys", "Flags", "REG_SZ", 510)]),
]

EXTRA_CATEGORIES = {
    "Телеметрия и приватность": ["tele_tasks", "advertising_id", "lockscreen_ads", "activity", "recall"],
    "Производительность": ["power_throttling", "visual_perf", "startup_delay", "menu_delay",
                           "fast_shutdown", "ntfs_lastaccess", "bg_apps", "delivery_opt"],
    "Игры": ["gaming_mode", "game_profile", "net_throttle", "hags", "mouse_accel", "sticky_keys"],
    "Интерфейс и удобство": ["classic_menu", "taskbar_left", "this_pc", "show_ext", "show_hidden",
                             "clipboard_history", "long_paths", "verbose_boot", "storage_sense"],
    "Лишнее и реклама": ["widgets", "cortana", "websearch", "edge_bg"],
}

EXTRA_RECOMMENDED = ["tele_tasks", "advertising_id", "lockscreen_ads", "activity",
                     "startup_delay", "menu_delay", "fast_shutdown", "edge_bg", "show_ext",
                     "delivery_opt", "sticky_keys"]

EXTRA_RISKY = {
    "visual_perf": "Интерфейс станет проще: без анимаций и прозрачности.",
    "gaming_mode": "Фоновые программы получат меньше времени процессора.",
    "net_throttle": "Меняет сетевые параметры; откатите при проблемах со звуком/сетью.",
    "hags": "Зависит от драйвера; нужна перезагрузка. При артефактах — откатите.",
    "bg_apps": "Приложения Store (Почта, Календарь…) не будут присылать уведомления в фоне.",
    "recall": "Отключает функции ИИ Windows (Recall, Copilot).",
    "cortana": "Полностью отключает Cortana.",
    "fast_shutdown": "Несохранённые данные в зависших программах могут быть потеряны.",
}

NEEDS_EXPLORER = {"visual_perf", "classic_menu", "taskbar_left", "show_ext", "show_hidden",
                  "this_pc", "widgets"}
NEEDS_REBOOT = {"hags", "gaming_mode", "long_paths", "power_throttling", "game_profile",
                "net_throttle", "ntfs_lastaccess", "mouse_accel"}
